- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/dto/VidInfoDTO.java
- id-repository/id-repository-vid-service/src/main/java/io/mosip/idrepository/vid/service/impl/VidServiceImpl.java
> [MOSIP-10170] updated retreiveVIDSforUIN api to return vid type in

- id-repository/bioextractor-service/Dockerfile
- id-repository/bioextractor-service/configure_start.sh
- id-repository/credential-request-generator/Dockerfile
- id-repository/credential-service/Dockerfile
- id-repository/id-repository-identity-service/Dockerfile
- id-repository/id-repository-salt-generator/Dockerfile
- id-repository/id-repository-vid-service/Dockerfile
Added/Enabled Docker user and upgraded biosdk installer script as per standard with other services.
> Added/Enabled Docker user and upgraded biosdk installer script

- id-repository/bioextractor-service/Dockerfile
No default sudo command present. installing sudo manually
> Install sudo command

- id-repository/id-repository-identity-service/Dockerfile
Added echo to check files downloaded inside loader path.
> Testing for loader path environment variable.

- id-repository/credential-request-generator/src/main/java/io/mosip/credential/request/generator/dto/CredentialStatusEvent.java
- id-repository/credential-request-generator/src/main/java/io/mosip/credential/request/generator/util/RestUtil.java
- id-repository/credential-service/src/main/java/io/mosip/credentialstore/dto/CryptomanagerRequestDto.java
- id-repository/credential-service/src/main/java/io/mosip/credentialstore/exception/DataEncryptionFailureException.java
- id-repository/credential-service/src/main/java/io/mosip/credentialstore/exception/SignatureException.java
- id-repository/id-repository-credentials-feeder/src/main/java/io/mosip/idrepository/credentialsfeeder/config/CredentialsFeederConfig.java
- id-repository/id-repository-credentials-feeder/src/main/java/io/mosip/idrepository/credentialsfeeder/step/CredentialsFeedingWriter.java
> [MOSIP-13847] added idvId decryption to credential writer

- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/repository/CredentialRequestStatusRepo.java
Fix for updated UIN details not publishing for IDA.
> MOSIP-8596

- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/constant/CredentialRequestStatusLifecycle.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/manager/CredentialServiceManager.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/manager/CredentialStatusManager.java
Event Publishing for e-KYC updates
> MOSIP-15014

- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/manager/CredentialServiceManager.java
Update UIN-Multiple credential issuing for OVP has been fixed
> Update UIN-Multiple credential issuing for OVP has been fixed

- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/constant/IdRepoConstants.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/dto/IDAEventDTO.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/dto/IDAEventsDTO.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/helper/IdRepoWebSubHelper.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/manager/CredentialServiceManager.java
- id-repository/id-repository-identity-service/src/test/java/io/mosip/idrepository/identity/test/service/impl/IdRepoServiceTest.java
- id-repository/id-repository-vid-service/src/test/java/io/mosip/idrepository/vid/controller/VidControllerTest.java
This reverts commit a95c33396a05ce957088cb4fe3c3c657dd5137dd.
> Revert "Corrected AuthType status event model (#292)"

- id-repository/id-repository-identity-service/pom.xml
> [MOSIP-15100] updated pom to fix bioapifactory parseexception missing

- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/builder/IdentityIssuanceProfileBuilder.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/manager/CredentialStatusManager.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/util/CryptoUtil.java
- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/helper/AnonymousProfileHelper.java
- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/helper/ChannelInfoHelper.java
- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/interceptor/IdRepoEntityInterceptor.java
- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/service/impl/IdRepoDraftServiceImpl.java
- id-repository/id-repository-vid-service/src/main/java/io/mosip/idrepository/vid/interceptor/IdRepoVidEntityInterceptor.java
- id-repository/id-repository-vid-service/src/main/java/io/mosip/idrepository/vid/service/impl/VidServiceImpl.java
[MOSIP-17758] fixed patch vid authorized user details #
[MOSIP-17758]: https://mosip.atlassian.net/browse/MOSIP-17758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixed Anonymous Profile issues

- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/helper/AnonymousProfileHelper.java
#	id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/helper/AnonymousProfileHelper.java
> [MOSIP-18202] Updated anonymous profile bio data handling

- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/constant/IdRepoConstants.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/helper/RestHelper.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/util/RestUtil.java
* Added caching of salt (#410)
#	id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/security/IdRepoSecurityManager.java
#	id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/repository/UinEncryptSaltRepo.java
#	id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/repository/UinHashSaltRepo.java
* Added rest util
* Added missing constant
* Fixed log
> Fix rest helper issue (#416)

- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/constant/IdRepoConstants.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/security/IdRepoSecurityManager.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/util/SaltUtil.java
- id-repository/id-repository-core/src/test/java/io/mosip/idrepository/core/test/util/SaltUtilTest.java
- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/service/impl/IdRepoProxyServiceImpl.java
- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/service/impl/IdRepoServiceImpl.java
- id-repository/id-repository-vid-service/src/main/java/io/mosip/idrepository/vid/service/impl/VidServiceImpl.java
* Changed salt id configuration logic
* Removed unwanted import
>  MOSIP-18522-Changed salt id computation logic and configuration (#414)

- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/dto/AuthTypeStatusRequestDto.java
- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/controller/IdRepoController.java
> [MOSIP-18980] updated IdType as Optional queryParam for AuthTypeStatus

- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/builder/RestRequestBuilder.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/config/IdRepoDataSourceConfig.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/util/EnvUtil.java
> [MOSIP-18655] Made EnvUtil as primary

- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/util/EnvUtil.java
This reverts commit 8a8f39ae588550a00fcf38b6051cd772ee31d1d1.
> [MOSIP-18655] Reverted EnvUtil with RefreshScope commit

- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/builder/IdentityIssuanceProfileBuilder.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/helper/IdRepoWebSubHelper.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/manager/CredentialStatusManager.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/util/EnvUtil.java
- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/config/IdRepoConfig.java
- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/helper/AnonymousProfileHelper.java
- id-repository/id-repository-vid-service/src/main/java/io/mosip/idrepository/vid/config/VidRepoConfig.java
> [MOSIP-19480] added thread pool with config prop and logic to monitor

- id-repository/credential-service/src/main/java/io/mosip/credentialstore/provider/impl/IdAuthProvider.java
This reverts commit a84f04b8b0deabee852362e1211f16ad49eab667.
> Revert "Added debug log for the cred demo data"

- id-repository/id-repository-core/src/test/java/io/mosip/idrepository/core/manager/partner/PartnerServiceManagerTest.java
> Created test class for PartnerServiceManager

- id-repository/credential-request-generator/src/test/java/io/mosip/credential/request/generator/interceptor/CredentialTransactionInterceptorTest.java
> Created test class for CredentialTransactionInterceptor

- id-repository/id-repository-identity-service/src/test/java/io/mosip/idrepository/identity/helper/VidDraftHelperTest.java
> Created test class for VidDraftHelper

- id-repository/credential-request-generator/src/test/java/io/mosip/credential/request/generator/init/CredentialInitializerTest.java
> Created test class for CredentialInitializer

- id-repository/credential-request-generator/src/test/java/io/mosip/credential/request/generator/util/RestUtilTest.java
- id-repository/id-repository-core/src/test/java/io/mosip/idrepository/core/manager/CredentialStatusManagerTest.java
> Created test class for CredentialStatusManager 

- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/controller/IdRepoController.java
- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/dto/AttributeListDto.java
- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/dto/RidDto.java
- id-repository/id-repository-identity-service/src/test/java/io/mosip/idrepository/identity/test/controller/IdRepoControllerTest.java
> updated the API endpoint and response attribute

- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/controller/IdRepoController.java
- id-repository/id-repository-identity-service/src/test/resources/application-test.properties
- id-repository/id-repository-identity-service/src/test/resources/application.properties
#12th task
added id and version
> [MOSIP-24670] Made corrections in api body

- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/logger/IdRepoAspectLogger.java
- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/service/impl/IdRepoProxyServiceImpl.java
- id-repository/id-repository-vid-service/src/main/java/io/mosip/idrepository/vid/service/impl/VidServiceImpl.java
Reverts mosip/id-repository#811
Since these changes are creating some null pointer exception
> Revert "MOSIP-29280, MOSIP-29281 Performance fixes"

- .github/workflows/push-trigger.yml
> [MOSIP-29163] updated workflow

- apitest/pom.xml
- apitest/testNgXmlFiles/IdrepositoryApi.xml
Upgraded Id Repository API automation test suite to JAVA 21.
> MOSIP-32363 JAVA 21 upgrade

- id-repository/credential-request-generator/src/main/java/io/mosip/credential/request/generator/util/CacheUtil.java
- id-repository/credential-service/src/main/java/io/mosip/credentialstore/util/PolicyUtil.java
- id-repository/credential-service/src/main/java/io/mosip/credentialstore/util/WebSubUtil.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/config/RedisCacheConfig.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/config/SimpleCacheConfig.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/constant/IdRepoConstants.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/manager/partner/PartnerServiceManager.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/repository/UinEncryptSaltRepo.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/repository/UinHashSaltRepo.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/security/IdRepoSecurityManager.java
- id-repository/id-repository-core/src/test/resources/application-test.properties
Reverts mosip/id-repository#956
> Revert "[ES-803]"

- apitest/Dockerfile
- apitest/entrypoint.sh
- apitest/pom.xml
- apitest/src/main/resources/idRepository/ReactivateVIDsForUIN/ReactivateVIDsForUIN.yml
- apitest/src/main/resources/idRepository/RetrieveAuthTypeStatus/RetrieveAuthTypeStatus.yml
- apitest/src/main/resources/idRepository/UpdateVIDStatus/UpdateVidStatus.yml
- apitest/testNgXmlFiles/IdrepositoryApi.xml
Merged the codes from develop branch and updated the maven plugins for JAVA 21 upgrade
> MOSIP-32363 - Merged from develop branch and updated the maven plugins for JAVA21

- apitest/src/main/java/io/mosip/testrig/apirig/testrunner/MosipTestRunner.java
- id-repository/id-repository-vid-service/Dockerfile
Updated MosipTestRunner for fixing the build failure
> MOSIP-32460 - Updated MosipTestRunner for fixing the build failure

- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/service/impl/IdRepoProxyServiceImpl.java
* MOSIP-39903
* Fixed bdb issue
---------
> MOSIP-39903

- id-repository/credential-service/src/main/java/io/mosip/credentialstore/constants/ApiName.java
- id-repository/credential-service/src/main/java/io/mosip/credentialstore/util/IdrepositaryUtil.java
- id-repository/credential-service/src/test/java/io/mosip/credentialstore/test/util/IdrepositaryUtilTest.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/dto/IdRequestByIdDTO.java
- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/controller/IdRepoController.java
- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/dto/AuthorizedRolesDto.java
- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/validator/IdRequestValidator.java
- id-repository/id-repository-identity-service/src/test/java/io/mosip/idrepository/identity/test/controller/IdRepoControllerTest.java
[[ MOSIP-36288 ]](https://mosip.atlassian.net/browse/MOSIP-36288) release-1.2.2.x adding to release-1.3.x
> MOSIP-39985

- api-test/pom.xml
- updated the commons pom version
> MOSIP-41183 - updated the commons pom version

- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/constant/CredentialRequestStatusLifecycle.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/manager/CredentialStatusManager.java
- id-repository/id-repository-core/src/main/java/io/mosip/idrepository/core/repository/CredentialRequestStatusRepo.java
- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/service/impl/IdRepoServiceImpl.java
- id-repository/id-repository-identity-service/src/test/java/io/mosip/idrepository/identity/test/service/impl/IdRepoServiceTest.java
Instead of updatedBy or updtimes, introduced UPDATE status
> MOSIP-40982

- api-test/src/main/java/io/mosip/testrig/apirig/idrepo/testscripts/AddIdentity.java
- api-test/src/main/java/io/mosip/testrig/apirig/idrepo/testscripts/DeleteWithParam.java
- api-test/src/main/java/io/mosip/testrig/apirig/idrepo/testscripts/GetWithParam.java
- api-test/src/main/java/io/mosip/testrig/apirig/idrepo/testscripts/GetWithParamForAutoGenId.java
- api-test/src/main/java/io/mosip/testrig/apirig/idrepo/testscripts/PatchWithPathParamsAndBody.java
- api-test/src/main/java/io/mosip/testrig/apirig/idrepo/testscripts/PostWithOnlyPathParam.java
- api-test/src/main/java/io/mosip/testrig/apirig/idrepo/testscripts/PutWithPathParam.java
- api-test/src/main/java/io/mosip/testrig/apirig/idrepo/testscripts/SimplePost.java
- api-test/src/main/java/io/mosip/testrig/apirig/idrepo/testscripts/SimplePostForAutoGenId.java
- api-test/src/main/java/io/mosip/testrig/apirig/idrepo/testscripts/UpdateDraft.java
- api-test/src/main/java/io/mosip/testrig/apirig/idrepo/testscripts/UpdateIdentity.java
- api-test/src/main/java/io/mosip/testrig/apirig/idrepo/testscripts/UpdateIdentityForArrayHandles.java
Integrated SecurityXSSException in apitest-idrepo module to standardize XSS-related error handling. This ensures consistent exception throwing across the application wherever XSS protection checks fail. Improves security and maintainability by centralizing exception logic.
> MOSIP-40258: Standardized XSS Exception Handling in apitest-idrepo Module 

- api-test/src/main/java/io/mosip/testrig/apirig/idrepo/testscripts/SimplePostForAutoGenId.java
- api-test/src/main/java/io/mosip/testrig/apirig/idrepo/testscripts/UpdateIdentity.java
- api-test/src/main/java/io/mosip/testrig/apirig/idrepo/testscripts/UpdateIdentityForArrayHandles.java
- api-test/src/main/java/io/mosip/testrig/apirig/idrepo/utils/IdRepoArrayHandle.java
- api-test/src/main/java/io/mosip/testrig/apirig/idrepo/utils/IdRepoUtil.java
- api-test/src/main/resources/idRepository/responseCode.hbs
Added responseCode.hbs template for handling IDREPO-related error codes. Also removed unused commented variables for code cleanup.
> MOSIP-37218 Added responseCode.hbs file for IDREPO related error code and removed commented unused variables.

- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/validator/IdRequestValidator.java
[MOSIP-36427] - Invalid Input Parameter issues fixed for UIN, RegistrationId, verifiedAttributes
[MOSIP-36427]: https://mosip.atlassian.net/browse/MOSIP-36427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOSIP-36427] - Invalid Input Parameter issues fixed for UIN, RegistrationId, verifiedAttributes

- api-test/README.md
- api-test/pom.xml
- Updated commons released version
> MOSIP-41683  - Updated commons released version

- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/helper/AnonymousProfileHelper.java
- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/service/impl/IdRepoServiceImpl.java
- id-repository/id-repository-identity-service/src/test/java/io/mosip/idrepository/identity/test/helper/AnonymousProfileHelperTest.java
[MOSIP-41324] Duplicate Biometric Reference UUIDs Causing ConstraintViolationError
[MOSIP-41324]: https://mosip.atlassian.net/browse/MOSIP-41324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOSIP-41324]Merge pull request #1241 from dst1201/MOSIP-41486_release-1.2.2.x

- id-repository/id-repository-identity-service/src/main/java/io/mosip/idrepository/identity/validator/IdRequestValidator.java
[MOSIP-36427] - Invalid Input Parameter issues fixed for UIN, RegistrationId, verifiedAttributes
[MOSIP-36427]: https://mosip.atlassian.net/browse/MOSIP-36427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOSIP-36427]Merge pull request #1304 from dst1201/MOSIP-41486_release-1.2.2.x

- api-test/src/main/resources/idRepository/RetrieveIdentityPost/retrieveIdentityTempPost.hbs
Updates request for RetrieveIdentity Post
> MOSIP-42538 : Updated idvid changes in develop branch

- docs/design/packet-processing-flow.md
[MOSIP-42837] Added the packet processing flow in the design document
[MOSIP-42837]: https://mosip.atlassian.net/browse/MOSIP-42837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOSIP-42837] Added the packet processing flow in the design document
